title: Deepak George Thomas
logo: /assets/img/chicao_photo.jpg
description: 
<br><br>
email:dgthomas@iastate.edu
<br><br>
<a href="https://www.linkedin.com/in/deepak-george-thomas-605626133/">View My Linkedin Profile</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
