title: Deepak George Thomas
logo: /assets/img/chicago_photo.jpg
description: 
email dgthomas@iastate.edu
<a href="https://www.linkedin.com/in/deepak-george-thomas-605626133/">View My Linkedin Profile</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
