title: Deepak George Thomas
logo: /assets/img/chicago_photo.jpg
description: 
 "Email:dgthomas@iastate.edu"
 <br><br>
 <a href="https://www.linkedin.com/in/deepak-george-thomas-605626133/"> Linkedin </a>
google_analytics:
theme: jekyll-theme-minimal
